image: macos-14 # Или конкретная версия macOS, если требуется (например, macos-13)

stages:
  - build

variables:
  FLUTTER_VERSION: "3.0.0" # Актуальная версия Flutter (замените на нужную)
  BUNDLE_ID: "kz.kdb.app.cabinet_mobile" # Идентификатор вашего приложения

before_script:
  - eval "$(/opt/homebrew/bin/brew shellenv)"
  - brew install git ruby # Ruby нужен для fastlane
  - gem install bundler --no-document
  - bundle install # Установка зависимостей fastlane (из Gemfile, если есть)
  - git config --global user.email "ci@example.com"
  - git config --global user.name "GitLab CI"
  - flutter channel stable
  - flutter upgrade $FLUTTER_VERSION
  - flutter pub get

build_ios:
  stage: build
  script:
    - bundle exec fastlane match development # Используем development сертификаты
    - bundle exec fastlane build_ios # Сборка проекта с использованием fastlane
  artifacts:
    paths:
      - build/ios/ipa/*.ipa
    expire_in: 30 days
  only:
    - main

cache:
  paths:
    - .pub-cache
    - vendor/bundle # Кэш Bundler