name: cabinet_mobile
description: "kdb cabinet mobile version"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^5.0.2
  unique_identifier: ^0.3.0
  rflutter_alert: ^2.0.7
  qr_code_scanner: ^1.0.1
  flutter_masked_text2: ^0.9.1
  intl: ^0.17.0
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/logo.png
     - assets/