name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest # или specific version, если нужно
    strategy:
      matrix:
        target: [apk, ipa] # Сборка для Android и iOS

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Укажите нужную версию Flutter

      - run: flutter pub get

      - name: Build Android
        if: matrix.target == 'apk'
        run: flutter build apk --release

      - name: Build iOS
        if: matrix.target == 'ipa'
        run: flutter build ipa --release --export-options export.plist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-build
          path: build/${{ matrix.target }}
